### ISSUE TITLE
Requirements, User Stories, Backlog and Planning

### ISSUE THREAD

**Issue by BacLuc** [ase-23-the-bald-owls/documentation#3]
- Home Page with products
- Backend to add products (+ authentication)
- search and filter on home
- shopping cart
- payment (+ create customer)
- backend to view orders
- payment with stripe
- set order to shipped
- send email when order is created
- send email when order is shipped
- login for customer
- login for seller (Optional)

**Comment by haznai** [comment]
## Description of Requirements task
You should organize your requirements into three categories: 
- user requirements (i.e., expected features and behaviors of the final product), 
- functional requirements (i.e., detailed software or infrastructure requirements or limitations that must apply to the final product)
- non-functional requirements (i.e., specific characteristics or behaviors of the system must comply with, that however do not constitute a usable software feature).

Ensure your requirements are concise, address only one single aspect of the product, and are as detailed as it is feasible for you to be at this stage.

## Sketch answer to the Requirements tasks (Final in LaTeX document)
Important to note is that we are a small team of three developers building an e-commerce shop mostly from scratch. Therefore, we are careful to list a set of requirements that are feasible for use to achieve in small sprints.

### User Requirements
- Shop page where the trading cards are listed
- Search and filter function for the list of trading cards 
- Shopping cart that contains products the user is planning to buy
- Checkout process with a variety of common payment methods
- Detailed product page where the quality, rarity, and authenticity of the trading card is visible
- Possibility of creating an account
- Personal orders page where the state of each order is visible
- A page where cards can be handed in for inspection (if the users wishes to sell something)
- Subscription option for monthly booster pack deliveries
- Backend where the facilitating stakeholders can add and edit products
- Backend where the management of orders is possible.

### Functional Requirements
- Authentication for the access to the backend
- Frontend state management
- Database persisting all orders and user profiles
- E-Mail service that notifies the user when the order is created and shipped
- Hosting for the backend and frontend as a single codebase

### Non-Functional Requirements
- Good and simple UI/UX design

**Comment by haznai** [comment]
## Description of User Story task

In your report, you are expected to at least include a user story for each feature or user requirement you have specified in the requirements section. These should be one or two sentences capturing what the user wants/needs to achieve. Remember that a good user story is: **I**ndependent (i.e., achieves a goal regardless of there being other stories in the pool), **N**egotiable (i.e., can open a discussion with your client), **V**aluable (i.e., the story can aid the team in developing the required support), **E**stimable (i.e., can be developed into the software directly), **S**mall, and **T**estable (i.e., the client can autonomously perform the story). Furthermore, ensure your stories follow the following structure:

```
Decision: <Must/Should/Could/Won't>
Requirement: <requirement given above it addresses>
T-Shirt: <S/M/L/XL>
As a: <as a section>
I want: <I want section>
So that: <so that section>
```

## Sketch Answer to the User Story task (Final in LaTeX Document)

```
Decision: Must
Requirement: Shop page where the trading cards are listed
T-Shirt: XL
As a: Regular Customer
I want: Shop page where the trading cards are listed
So that: I can see which products the store has for sale
```

```
Decision: Must
Requirement: Search and filter function for the list of trading cards
T-Shirt: M
As a: Regular Customer
I want: Search and filter function
So that: trading cards that fit my exact requirements
```

```
Decision: Must
Requirement: Shopping cart that contains products the user is planning to buy
T-Shirt: L
As a: Regular Customer
I want: A shopping cart
So that: I can check which cards I am currently considering to buy
```

```
Decision: Must
Requirement: Checkout process with a variety of common payment methods
T-Shirt: S
As a: Regular Customer
I want: A checkout process
So that: I can place my order in a fast and convenient manner
```

```
Decision: Should
Requirement: Detailed product page where the quality, rarity, and authenticity of the trading card is visible
T-Shirt: M
As a: Regular Custmer
I want: Detailed product page
So that: I can see if the specific trading card in question fits my requirements
```

```
Decision: Should
Requirement: Possibility of creating an account
T-Shirt: L
As a: Regular Customer
I want: have the possibility to create an account
So that: future visits to the store are more convenient
```

```
Decision: Could
Requirement: Personal orders page where the state of each order is visible
T-Shirt: M
As a: Regular Customer
I want: A personal orders page
So that: I can easily track the state of my placed orders
```

```
Decision: Won't
Requirement: A page where cards can be handed in for inspection
T-Shirt: L
As a: Regular Customer 
I want: A page where cards can be handed in for inspection
So that: I can have the store rate and sell the cards for me
```

```
Decision: Could
Requirement: Subscription option for monthly booster pack deliveries
T-Shirt: L
As a: Subscribing Customer
I want: A subscription option 
So that: I can receive monthly booster packs without explicity ordering them each time
```

```
Decision: Must
Requirement: Backend where the facilitating stakeholders can add and edit products
T-Shirt: XL
As a: Member of the Rating staff
I want: Backend where you can add and edit products
So that: I can maintain an up-to-date inventory
```

```
Decision: Should
Requirement: Backend where the management of orders is possible
T-Shirt: M
As a: Customer Service Staff member
I want: Backend to manage orders
So that: Make sure the customers receive and are happy with the product
```

**Comment by haznai** [comment]
Backlog and planning have been implemented in the project as issues and user stories
